/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type ContactPanelSection = {
	_type: 'contactPanelSection';
	foregroundColour?: 'primary' | 'secondary' | 'accent';
	backgroundColour?: 'background' | 'muted' | 'warm' | 'primaryTint';
	heading?: HeadingText;
	body?: string;
	email?: string;
};

export type ProjectDiscoveryModule = {
	_type: 'projectDiscoveryModule';
	foregroundColour?: 'primary' | 'secondary' | 'accent';
	backgroundColour?: 'background' | 'muted' | 'warm' | 'primaryTint';
	heading?: HeadingText;
	intro?: string;
};

export type HomeHeroSection = {
	_type: 'homeHeroSection';
	eyebrow?: string;
	foregroundColour?: 'primary' | 'secondary' | 'accent';
	backgroundColour?: 'background' | 'muted' | 'warm' | 'primaryTint';
	heading?: HeadingText;
	body?: string;
	image?: ImageWithAlt;
};

export type FeaturesSection = {
	_type: 'featuresSection';
	foregroundColour?: 'primary' | 'secondary' | 'accent';
	backgroundColour?: 'background' | 'muted' | 'warm' | 'primaryTint';
	eyebrow?: string;
	heading?: HeadingText;
	intro?: string;
	textAlignment?: 'left' | 'center' | 'right';
	features?: Array<
		{
			_key: string;
		} & FeatureItem
	>;
};

export type ImageTextSection = {
	_type: 'imageTextSection';
	foregroundColour?: 'primary' | 'secondary' | 'accent';
	backgroundColour?: 'background' | 'muted' | 'warm' | 'primaryTint';
	eyebrow?: string;
	heading?: HeadingText;
	body?: RichText;
	image?: ImageWithAlt;
	imagePosition?: 'left' | 'right';
	textAlignment?: 'left' | 'center' | 'right';
	callToActions?: Array<
		{
			_key: string;
		} & SectionCallToAction
	>;
};

export type ImageBackgroundSection = {
	_type: 'imageBackgroundSection';
	foregroundColour?: 'primary' | 'secondary' | 'accent';
	eyebrow?: string;
	heading?: HeadingText;
	body?: RichText;
	backgroundImage?: ImageWithAlt;
	textAlignment?: 'left' | 'center' | 'right';
	callToActions?: Array<
		{
			_key: string;
		} & SectionCallToAction
	>;
};

export type FeatureItem = {
	_type: 'featureItem';
	title?: string;
	description?: string;
	icon?: LucideIcon;
	iconColor?: 'primary' | 'secondary' | 'accent';
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
	_type: 'imageWithAlt';
	asset?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	alt?: string;
};

export type HomePageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'homePage';
};

export type ContactPageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'contactPage';
};

export type PageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'page';
};

export type SectionCallToAction = {
	_type: 'sectionCallToAction';
	label?: string;
	destinationType?: 'internal' | 'external';
	page?: HomePageReference | ContactPageReference | PageReference;
	externalUrl?: string;
	openInNewTab?: boolean;
	style?: 'match' | 'primary' | 'secondary' | 'outline';
};

export type SiteLink = {
	_type: 'siteLink';
	label?: string;
	destinationType?: 'internal' | 'external';
	page?: HomePageReference | ContactPageReference | PageReference;
	externalUrl?: string;
	openInNewTab?: boolean;
};

export type HeadingText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: Array<{
		source?: string;
		_type: 'foregroundColour';
		_key: string;
	}>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type RichText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'blockquote';
	listItem?: never;
	markDefs?: null;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type SiteNavigation = {
	_id: string;
	_type: 'siteNavigation';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	headerLinks?: Array<
		{
			_key: string;
		} & SiteLink
	>;
	footerGroups?: Array<{
		heading?: string;
		links?: Array<
			{
				_key: string;
			} & SiteLink
		>;
		_type: 'footerLinkGroup';
		_key: string;
	}>;
};

export type ContactPage = {
	_id: string;
	_type: 'contactPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	seo?: {
		title?: string;
		description?: string;
		socialImage?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
	sections?: Array<
		| ({
				_key: string;
		  } & ContactPanelSection)
		| ({
				_key: string;
		  } & ImageBackgroundSection)
		| ({
				_key: string;
		  } & ImageTextSection)
		| ({
				_key: string;
		  } & FeaturesSection)
	>;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type HomePage = {
	_id: string;
	_type: 'homePage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	seo?: {
		title?: string;
		description?: string;
		socialImage?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
	sections?: Array<
		| ({
				_key: string;
		  } & HomeHeroSection)
		| ({
				_key: string;
		  } & ImageBackgroundSection)
		| ({
				_key: string;
		  } & ImageTextSection)
		| ({
				_key: string;
		  } & FeaturesSection)
		| ({
				_key: string;
		  } & ProjectDiscoveryModule)
	>;
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	seo?: {
		title?: string;
		description?: string;
		socialImage?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
	sections?: Array<
		| ({
				_key: string;
		  } & ImageBackgroundSection)
		| ({
				_key: string;
		  } & ImageTextSection)
		| ({
				_key: string;
		  } & FeaturesSection)
	>;
};

export type LucideIcon = string;

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| ContactPanelSection
	| ProjectDiscoveryModule
	| HomeHeroSection
	| FeaturesSection
	| ImageTextSection
	| ImageBackgroundSection
	| FeatureItem
	| SanityImageAssetReference
	| ImageWithAlt
	| HomePageReference
	| ContactPageReference
	| PageReference
	| SectionCallToAction
	| SiteLink
	| HeadingText
	| RichText
	| SiteNavigation
	| ContactPage
	| SanityImageCrop
	| SanityImageHotspot
	| HomePage
	| Page
	| LucideIcon
	| Slug
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: cmsPageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {		_id,		_type,		title,		slug,		seo {			title,			description,			socialImage		},		sections[] {			_key,			_type,			_type == "imageBackgroundSection" => {				foregroundColour,				eyebrow,				heading,				body,				textAlignment,				backgroundImage {					alt,					asset {						asset,						crop,						hotspot					}				},								callToActions[] {					_key,					label,					style,					destinationType,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current,					"internalPageType": page->_type				}			},			_type == "imageTextSection" => {				foregroundColour,				backgroundColour,				eyebrow,				heading,				body,				imagePosition,				textAlignment,				image {					alt,					asset {						asset,						crop,						hotspot					}				},								callToActions[] {					_key,					label,					style,					destinationType,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current,					"internalPageType": page->_type				}			},			_type == "featuresSection" => {				foregroundColour,				backgroundColour,				eyebrow,				heading,				intro,				textAlignment,				features[] {					_key,					title,					description,					icon,					iconColor				}			}		}	}
export type CmsPageQueryResult = {
	_id: string;
	_type: 'page';
	title: string | null;
	slug: Slug | null;
	seo: {
		title: string | null;
		description: string | null;
		socialImage: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		} | null;
	} | null;
	sections: Array<
		| {
				_key: string;
				_type: 'featuresSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				intro: string | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				features: Array<{
					_key: string;
					title: string | null;
					description: string | null;
					icon: LucideIcon | null;
					iconColor: 'accent' | 'primary' | 'secondary' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'imageBackgroundSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				body: RichText | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				backgroundImage: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToActions: Array<{
					_key: string;
					label: string | null;
					style: 'match' | 'outline' | 'primary' | 'secondary' | null;
					destinationType: 'external' | 'internal' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
					internalPageType: 'contactPage' | 'homePage' | 'page' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'imageTextSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				body: RichText | null;
				imagePosition: 'left' | 'right' | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				image: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToActions: Array<{
					_key: string;
					label: string | null;
					style: 'match' | 'outline' | 'primary' | 'secondary' | null;
					destinationType: 'external' | 'internal' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
					internalPageType: 'contactPage' | 'homePage' | 'page' | null;
				}> | null;
		  }
	> | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: siteNavigationQuery
// Query: *[_type == "siteNavigation" && _id == "siteNavigation"][0] {		headerLinks[] {			_key,			label,			destinationType,			externalUrl,			openInNewTab,			"pageSlug": page->slug.current,			"internalPageType": page->_type		},		footerGroups[] {			_key,			heading,			links[] {				_key,				label,				destinationType,				externalUrl,				openInNewTab,				"pageSlug": page->slug.current,				"internalPageType": page->_type			}		}	}
export type SiteNavigationQueryResult = {
	headerLinks: Array<{
		_key: string;
		label: string | null;
		destinationType: 'external' | 'internal' | null;
		externalUrl: string | null;
		openInNewTab: boolean | null;
		pageSlug: string | null;
		internalPageType: 'contactPage' | 'homePage' | 'page' | null;
	}> | null;
	footerGroups: Array<{
		_key: string;
		heading: string | null;
		links: Array<{
			_key: string;
			label: string | null;
			destinationType: 'external' | 'internal' | null;
			externalUrl: string | null;
			openInNewTab: boolean | null;
			pageSlug: string | null;
			internalPageType: 'contactPage' | 'homePage' | 'page' | null;
		}> | null;
	}> | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"][0] {		seo { title, description, socialImage { asset { asset, crop, hotspot } } },		sections[] {			_key,			_type,			_type == "homeHeroSection" => {				eyebrow,				foregroundColour,				backgroundColour,				heading,				body,				image { alt, asset { asset, crop, hotspot } }			},			_type == "projectDiscoveryModule" => { foregroundColour, backgroundColour, heading, intro },						_type == "imageBackgroundSection" => {				foregroundColour,				eyebrow,				heading,				body,				textAlignment,				backgroundImage { alt, asset { asset, crop, hotspot } },								callToActions[] {					_key,					label,					style,					destinationType,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current,					"internalPageType": page->_type				}			},			_type == "imageTextSection" => {				foregroundColour,				backgroundColour,				eyebrow,				heading,				body,				imagePosition,				textAlignment,				image { alt, asset { asset, crop, hotspot } },								callToActions[] {					_key,					label,					style,					destinationType,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current,					"internalPageType": page->_type				}			},			_type == "featuresSection" => {				foregroundColour,				backgroundColour,				eyebrow,				heading,				intro,				textAlignment,				features[] { _key, title, description, icon, iconColor }			}		}	}
export type HomePageQueryResult = {
	seo: {
		title: string | null;
		description: string | null;
		socialImage: {
			asset: {
				asset: null;
				crop: null;
				hotspot: null;
			} | null;
		} | null;
	} | null;
	sections: Array<
		| {
				_key: string;
				_type: 'featuresSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				intro: string | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				features: Array<{
					_key: string;
					title: string | null;
					description: string | null;
					icon: LucideIcon | null;
					iconColor: 'accent' | 'primary' | 'secondary' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'homeHeroSection';
				eyebrow: string | null;
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				heading: HeadingText | null;
				body: string | null;
				image: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
		  }
		| {
				_key: string;
				_type: 'imageBackgroundSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				body: RichText | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				backgroundImage: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToActions: Array<{
					_key: string;
					label: string | null;
					style: 'match' | 'outline' | 'primary' | 'secondary' | null;
					destinationType: 'external' | 'internal' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
					internalPageType: 'contactPage' | 'homePage' | 'page' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'imageTextSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				body: RichText | null;
				imagePosition: 'left' | 'right' | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				image: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToActions: Array<{
					_key: string;
					label: string | null;
					style: 'match' | 'outline' | 'primary' | 'secondary' | null;
					destinationType: 'external' | 'internal' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
					internalPageType: 'contactPage' | 'homePage' | 'page' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'projectDiscoveryModule';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				heading: HeadingText | null;
				intro: string | null;
		  }
	> | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage" && _id == "contactPage"][0] {		seo { title, description, socialImage { asset { asset, crop, hotspot } } },		sections[] {			_key,			_type,			_type == "contactPanelSection" => {				foregroundColour,				backgroundColour,				heading,				body,				email,			},						_type == "imageBackgroundSection" => {				foregroundColour,				eyebrow,				heading,				body,				textAlignment,				backgroundImage { alt, asset { asset, crop, hotspot } },								callToActions[] {					_key,					label,					style,					destinationType,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current,					"internalPageType": page->_type				}			},			_type == "imageTextSection" => {				foregroundColour,				backgroundColour,				eyebrow,				heading,				body,				imagePosition,				textAlignment,				image { alt, asset { asset, crop, hotspot } },								callToActions[] {					_key,					label,					style,					destinationType,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current,					"internalPageType": page->_type				}			},			_type == "featuresSection" => {				foregroundColour,				backgroundColour,				eyebrow,				heading,				intro,				textAlignment,				features[] { _key, title, description, icon, iconColor }			}		}	}
export type ContactPageQueryResult = {
	seo: {
		title: string | null;
		description: string | null;
		socialImage: {
			asset: {
				asset: null;
				crop: null;
				hotspot: null;
			} | null;
		} | null;
	} | null;
	sections: Array<
		| {
				_key: string;
				_type: 'contactPanelSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				heading: HeadingText | null;
				body: string | null;
				email: string | null;
		  }
		| {
				_key: string;
				_type: 'featuresSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				intro: string | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				features: Array<{
					_key: string;
					title: string | null;
					description: string | null;
					icon: LucideIcon | null;
					iconColor: 'accent' | 'primary' | 'secondary' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'imageBackgroundSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				body: RichText | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				backgroundImage: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToActions: Array<{
					_key: string;
					label: string | null;
					style: 'match' | 'outline' | 'primary' | 'secondary' | null;
					destinationType: 'external' | 'internal' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
					internalPageType: 'contactPage' | 'homePage' | 'page' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'imageTextSection';
				foregroundColour: 'accent' | 'primary' | 'secondary' | null;
				backgroundColour: 'background' | 'muted' | 'primaryTint' | 'warm' | null;
				eyebrow: string | null;
				heading: HeadingText | null;
				body: RichText | null;
				imagePosition: 'left' | 'right' | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				image: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToActions: Array<{
					_key: string;
					label: string | null;
					style: 'match' | 'outline' | 'primary' | 'secondary' | null;
					destinationType: 'external' | 'internal' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
					internalPageType: 'contactPage' | 'homePage' | 'page' | null;
				}> | null;
		  }
	> | null;
} | null;
