/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type FeaturesSection = {
	_type: 'featuresSection';
	heading?: string;
	textAlignment?: 'left' | 'center' | 'right';
	features?: Array<
		{
			_key: string;
		} & FeatureItem
	>;
};

export type ImageTextSection = {
	_type: 'imageTextSection';
	heading?: string;
	body?: RichText;
	image?: ImageWithAlt;
	imagePosition?: 'left' | 'right';
	textAlignment?: 'left' | 'center' | 'right';
	callToAction?: SiteLink;
};

export type ImageBackgroundSection = {
	_type: 'imageBackgroundSection';
	heading?: string;
	body?: RichText;
	backgroundImage?: ImageWithAlt;
	textAlignment?: 'left' | 'center' | 'right';
	callToAction?: SiteLink;
};

export type FeatureItem = {
	_type: 'featureItem';
	title?: string;
	description?: string;
	icon?: 'sprout' | 'water' | 'sun' | 'idea' | 'partnership' | 'tree';
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
	_type: 'imageWithAlt';
	asset?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	alt?: string;
};

export type PageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'page';
};

export type SiteLink = {
	_type: 'siteLink';
	label?: string;
	destinationType?: 'page' | 'route' | 'external';
	page?: PageReference;
	route?: '/' | '/contact';
	externalUrl?: string;
	openInNewTab?: boolean;
};

export type RichText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'blockquote';
	listItem?: never;
	markDefs?: null;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type SiteNavigation = {
	_id: string;
	_type: 'siteNavigation';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	headerLinks?: Array<
		{
			_key: string;
		} & SiteLink
	>;
	footerGroups?: Array<{
		heading?: string;
		links?: Array<
			{
				_key: string;
			} & SiteLink
		>;
		_type: 'footerLinkGroup';
		_key: string;
	}>;
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	seo?: {
		title?: string;
		description?: string;
		socialImage?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
	sections?: Array<
		| ({
				_key: string;
		  } & ImageBackgroundSection)
		| ({
				_key: string;
		  } & ImageTextSection)
		| ({
				_key: string;
		  } & FeaturesSection)
	>;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| FeaturesSection
	| ImageTextSection
	| ImageBackgroundSection
	| FeatureItem
	| SanityImageAssetReference
	| ImageWithAlt
	| PageReference
	| SiteLink
	| RichText
	| SiteNavigation
	| Page
	| SanityImageCrop
	| SanityImageHotspot
	| Slug
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: cmsPageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {		_id,		_type,		title,		slug,		seo {			title,			description,			socialImage		},		sections[] {			_key,			_type,			_type == "imageBackgroundSection" => {				heading,				body,				textAlignment,				backgroundImage {					alt,					asset {						asset,						crop,						hotspot					}				},				callToAction {					label,					destinationType,					route,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current				}			},			_type == "imageTextSection" => {				heading,				body,				imagePosition,				textAlignment,				image {					alt,					asset {						asset,						crop,						hotspot					}				},				callToAction {					label,					destinationType,					route,					externalUrl,					openInNewTab,					"pageSlug": page->slug.current				}			},			_type == "featuresSection" => {				heading,				textAlignment,				features[] {					_key,					title,					description,					icon				}			}		}	}
export type CmsPageQueryResult = {
	_id: string;
	_type: 'page';
	title: string | null;
	slug: Slug | null;
	seo: {
		title: string | null;
		description: string | null;
		socialImage: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		} | null;
	} | null;
	sections: Array<
		| {
				_key: string;
				_type: 'featuresSection';
				heading: string | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				features: Array<{
					_key: string;
					title: string | null;
					description: string | null;
					icon: 'idea' | 'partnership' | 'sprout' | 'sun' | 'tree' | 'water' | null;
				}> | null;
		  }
		| {
				_key: string;
				_type: 'imageBackgroundSection';
				heading: string | null;
				body: RichText | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				backgroundImage: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToAction: {
					label: string | null;
					destinationType: 'external' | 'page' | 'route' | null;
					route: '/' | '/contact' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
				} | null;
		  }
		| {
				_key: string;
				_type: 'imageTextSection';
				heading: string | null;
				body: RichText | null;
				imagePosition: 'left' | 'right' | null;
				textAlignment: 'center' | 'left' | 'right' | null;
				image: {
					alt: string | null;
					asset: {
						asset: SanityImageAssetReference | null;
						crop: SanityImageCrop | null;
						hotspot: SanityImageHotspot | null;
					} | null;
				} | null;
				callToAction: {
					label: string | null;
					destinationType: 'external' | 'page' | 'route' | null;
					route: '/' | '/contact' | null;
					externalUrl: string | null;
					openInNewTab: boolean | null;
					pageSlug: string | null;
				} | null;
		  }
	> | null;
} | null;
